server:
  port: 7070

spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:6336/Shebao?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #username: zhengxin
    #password: pb%ek05l?N3w
    url:  jdbc:mysql://106.75.172.190:3306/application-service?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: TFS20200428
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh


#logging:
#  config: classpath:logback.xml

