server:
  port: 7070

spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:6336/Shebao?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #username: zhengxin
    #password: pb%ek05l?N3w
    url: jdbc:mysql://127.0.0.1:3306/shebao?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12231223
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh


#logging:
#  config: classpath:logback.xml

